//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForestMarathone
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForestMarathoneEntities : DbContext
    {
        public ForestMarathoneEntities()
            : base("name=ForestMarathoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<LoginHistory> LoginHistory { get; set; }
        public virtual DbSet<MarathonResults> MarathonResults { get; set; }
        public virtual DbSet<MarathonStatus> MarathonStatus { get; set; }
        public virtual DbSet<Participant> Participant { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sets> Sets { get; set; }
        public virtual DbSet<SponsoredParticipants> SponsoredParticipants { get; set; }
        public virtual DbSet<Sponsors> Sponsors { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeDistances> TypeDistances { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserStatus> UserStatus { get; set; }
    }
}
