//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForestMarathone
{
    using System;
    using System.Collections.Generic;
    
    public partial class SponsoredParticipants
    {
        public int Id { get; set; }
        public int ParticipantId { get; set; }
        public int SponsorId { get; set; }
        public decimal SponsoredMoney { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual Sponsors Sponsors { get; set; }
    }
}
